//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeAfter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanInfo
    {
        public string loanId { get; set; }
        public string loanCategory { get; set; }
        public string loanType { get; set; }
        public string loanAmount { get; set; }
        public string isPosLoan { get; set; }
        public Nullable<int> grossIncome { get; set; }
    }
}
