//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeAfter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOffer
    {
        public long OffID { get; set; }
        public Nullable<long> ReqID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<decimal> ApprovedAmmount { get; set; }
        public Nullable<decimal> TotalPayback { get; set; }
        public Nullable<int> IncreasePercent { get; set; }
        public Nullable<decimal> MonthlyAmount { get; set; }
        public Nullable<int> MonthCount { get; set; }
        public string Lender { get; set; }
        public Nullable<decimal> Ammount { get; set; }
        public string Duration { get; set; }
        public string Intrest { get; set; }
        public string LoanId { get; set; }
        public Nullable<double> annualFee { get; set; }
        public Nullable<bool> eligibility { get; set; }
        public Nullable<bool> isPreQualifyOffer { get; set; }
        public string minApr { get; set; }
        public string offerExpirationDate { get; set; }
        public string pendingOffers { get; set; }
        public string status { get; set; }
        public Nullable<int> term { get; set; }
        public string legalDisclosure { get; set; }
        public string maxMonthlyPayment { get; set; }
    }
}
