//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeAfter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmitOfferResponce
    {
        public int ConfirmOfferId { get; set; }
        public Nullable<int> userId { get; set; }
        public string loanId { get; set; }
        public string applicationId { get; set; }
        public string type { get; set; }
        public string reason { get; set; }
        public string message { get; set; }
    }
}
